name: Release
on:
  push:
    branches: [main] # remove later
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
